spring.application.name=calendar-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/calendar_app
spring.datasource.username=calendar_user
spring.datasource.password=calendar_pass
spring.flyway.baselineOnMigrate=true
mybatis.configuration.map-underscore-to-camel-case=true